name: CI

on:
  push:
    branches:
  pull:
    branches:
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Chechout source code
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '22'